before_script:
  - '[[ ! -e /.dockerenv ]] && exit 0'

stages:
  - phpunit
  # - deploy

variables:
  MYSQL_DATABASE: juanisoler
  MYSQL_ROOT_PASSWORD: secret

phpunit:php7.1:mysq:latest:
  stage: phpunit
  only:
    - develop
  image: zaherg/php-7.1-xdebug-alpine:latest
  services:
    - mysql:latest
  script:
    - sh .gitlab-ci.sh

deploy_develop:
   stage: deploy
   before_script:
     - mkdir -p ~/.ssh
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   script:
     - ssh sshuser@$DEV_SERVER "cd ~/www && git pull origin develop && ~/bin/composer install"
   environment:
     name: develop
     url: https://staging.juanisoler.com/
   only:
     - develop